### ISSUE TITLE
1.17.x build?

### ISSUE THREAD

**Issue by sudofox** [ImUrX/screencopy#1]
I'm still using 1.17.1 (with ViaFabric for 1.18+ support). Any chance of a native 1.17 build alongside the 1.18 one?

**Comment by ImUrX** [comment]
i will see if i have time to build it but you could try using [Earthcomputer's multiconnect](https://github.com/Earthcomputer/multiconnect) to do the reverse which lets you connect to 1.17 from 1.18

**Comment by sudofox** [comment]
Thanks! I actually have both ViaFabric and Multiconnect but am using 1.17.1 for both performance reasons and also because I have a lot of mods that haven't updated.

**Comment by ImUrX** [comment]
2 months late but i did it lol
