### ISSUE TITLE
ARM Compatibility

### ISSUE THREAD

**Issue by ChuckFaulker** [ImUrX/screencopy#4]
I'd love ARM compatibility to use with M1 MacOS. Thanks!

**Comment by ImUrX** [comment]
i need to update quite a lot of code because quilt launched 🙄

**Comment by ImUrX** [comment]
@ChuckFaulker I have uploaded a new version with ARM support in every platform. Sorry for the delay!

Have fun :p

**Comment by ImUrX** [comment]
btw do test it pls, i dont have a way to do it
